# Generated by Django 5.0.1 on 2024-01-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core1', '0002_car_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='level',
        ),
        migrations.AddField(
            model_name='car',
            name='valuation',
            field=models.IntegerField(default=0),
        ),
    ]
