# Generated by Django 5.0.1 on 2024-01-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core1', '0005_car_valuation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='level_1',
        ),
        migrations.RemoveField(
            model_name='car',
            name='level_2',
        ),
        migrations.RemoveField(
            model_name='car',
            name='level_3',
        ),
        migrations.AddField(
            model_name='car',
            name='level_s',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='valuation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
